#!/bin/bash
cd src
ls -d */ | while read i; do (
    cd "$i"
    echo "Running $i"
    dos2unix compile.bat run.bat > /dev/null 2>&1 
    sed -e 's/;/:/g' -e 's/\\/\//g' compile.bat | bash 2>&1 || { echo "Compile failed $i"; exit; }
    sed -e 's/;/:/g' -e 's/\\/\//g' run.bat | bash 2>&1 || echo "Run failed $i"
    echo 
)
done
