#!/bin/bash
if [ $# != 1 ]; then
    echo "usage: $0 # where # is the week number"
    exit 1
fi

week="week$1"
folder=tests/$week/
files=$(find $folder -name "*.txt" | while read i; do echo -n "$i "; done)
output=
testno=0
failed=0
for i in $files; do
    echo "Running ${i##$folder}"
    while read line || [ -n "$line" ]; do
        if [ ${line::1} = i ]; then
            src=${i##$folder}
            src=${src%%Test\.txt}
            output=$(echo -e "${line:1}" | java -cp src/$week $src)
        elif [ ${line::1} = e ]; then
            ((testno++))
            if [ "$output" != "$(echo -e "${line:1}" | tr -d '\r')" ]; then
                echo "Failed test number: $testno"
                echo "Expected: $(echo -e "${line:1}")"
                echo "Actual  : $output"
                ((failed++))
            fi
        fi
    done < "$i"
    echo
done
echo "Tests run: $testno,  Failures: $failed"