#!/bin/bash
if [ $# != 1 ]; then
    echo "usage: $0 # where # is the week number"
    exit 1
fi

# Compile class files
find src -name *.java | while read i; do
    javac $i
done

# Test java files
bash junit $1

# Test txt files
bash std $1