#!/bin/bash
if [ $# != 1 ]; then
    echo "usage: $0 # where # is the week number"
    exit 1
fi

week="week$1"

# Compile class files
javac -cp src/$week/*.java

# Test java files
bash junit $1

# Test txt files
bash std $1