#!/bin/bash
if ! (dpkg -s unzip 2>&1 > /dev/null); then
    echo "Install unzip first"
    echo "sudo apt update; sudo apt install unzip"
    exit 1
fi
if [ $# != 1 ]; then
    echo "usage: $0 # where # is the week number"
    exit 1
fi

week="week$1"
[ -d feedback/$week ] || mkdir -p feedback/$week
[ -d src ] || mkdir -p src

folder=students/$week/
find $folder -name *.zip | while read i; do
    rm -rf src/*
    unzip $i -d src
    cd src
    rm -rf __MACOSX
    find -maxdepth 1 -name "*.java" | grep -q "." || mv -f */* .
    cd ..
    feedback=${i%%\.zip}
    bash test $1 > feedback/$week/${feedback##$folder}.txt
done